#!/usr/bin/bash

#SBATCH --time=50:00:00
#SBATCH --partition=net-disk
##SBATCH --partition=shmem
#SBATCH --ntasks=1
##SBATCH --ntasks=24
#SBATCH --output=LOGS/pre_proc_meteo.job.o%j
#SBATCH --error=LOGS/pre_proc_meteo.job.e%j

#------------------------- array with days variables -----------------------------------------------------------------#
#today=("20201207" "20201201" "20191222" "20191111" "20190201" "20181028" "20180317" "20171112" "20160615" "20160228")

today=20191226
sub=6
#path="/fs/scratch/mare_exp/jacopo/PRE_PROC/METEO_OPERATIONAL/shydata/"
typ="an"
mod="5M"

for i in ${today[@]}
do
   #-------------- generate directories and indicate path --------------------#
   mkdir -p /fs/scratch/mare_exp/jacopo/PRE_PROC/METEO_OPERATIONAL/${i}_5M_an/
   path="/fs/scratch/mare_exp/jacopo/PRE_PROC/METEO_OPERATIONAL/${i}_5M_an/" 

   time /fs/scratch/mare_exp/jacopo/PRE_PROC/METEO_OPERATIONAL/extrct_frc.sh $i $sub $path $typ $mod 
done
