#!/usr/bin/bash

#SBATCH --time=50:00:00
#SBATCH --partition=net-disk
##SBATCH --partition=shmem
#SBATCH --ntasks=1
##SBATCH --ntasks=24
#SBATCH --output=LOGS/pre_proc_mare.job.o%j
#SBATCH --error=LOGS/pre_proc_mare.job.e%j


#today=("20201207" "20201201" "20191222")
today=20191223
sub=1
#path="/fs/scratch/mare_exp/jacopo/PRE_PROC/OCEAN_OPERATIONAL/20201208/"

for i in ${today[@]}
do
  #------------ generate directories and indicate path -------------------------#

  mkdir -p /fs/scratch/mare_exp/jacopo/PRE_PROC/OCEAN_OPERATIONAL/${i}_ocean_an/
  path="/fs/scratch/mare_exp/jacopo/PRE_PROC/OCEAN_OPERATIONAL/${i}_ocean_an/"

  time /fs/scratch/mare_exp/jacopo/PRE_PROC/OCEAN_OPERATIONAL/extrct_bnd.sh $today $sub $path
done

